// product
export const PRODUCT_LIST         = 'PRODUCT_LIST';
export const PRODUCT_UPDATE       = 'PRODUCT_LIST_FETCH';
export const PRODUCT_DETAIL_FETCH = 'PRODUCT_DETAIL_FETCH';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_ADD_PICTURES = 'PRODUCT_ADD_PICTURES';

export default {PRODUCT_LIST,
    PRODUCT_UPDATE,
    PRODUCT_DETAIL_FETCH,
    PRODUCT_SAVE_SUCCESS,
    PRODUCT_ADD_PICTURES,
};
