# Generated by Django 2.2.2 on 2019-06-29 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraframe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 14, 1, 26, 698040)),
        ),
    ]
