# Generated by Django 2.2.2 on 2019-06-29 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20190629_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraframe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 17, 20, 19, 32280)),
        ),
        migrations.AlterField(
            model_name='objectcategory',
            name='camera_frame',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='object_categories', to='restapi.CameraFrame'),
        ),
        migrations.AlterField(
            model_name='objectcategory',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_categories', to='restapi.Zone'),
        ),
    ]
